import { ComponentTypeEnum, ComponentCategoryEnum, type ComponentMetadata } from '@wect/type';

// 组件列表 默认组件
const initComponentList: ComponentMetadata[] = [
  {
    componentId: 1,
    componentName: 'Flex',
    componentType: ComponentTypeEnum.FLEX,
    category: ComponentCategoryEnum.LAYOUT,
    tags: ['布局', 'Flex'],
    version: '1.0.0',
    description: '用于布局的Flex组件',
    icon: 'flex-icon',
  },
  {
    componentId: 2,
    componentName: 'Text',
    componentType: ComponentTypeEnum.TEXT,
    category: ComponentCategoryEnum.BASIC,
    tags: ['文本', 'Text'],
    version: '1.0.0',
    description: '用于显示文本的组件',
    icon: 'text-icon',
  },
  {
    componentId: 3,
    componentName: 'Button',
    componentType: ComponentTypeEnum.BUTTON,
    category: ComponentCategoryEnum.BASIC,
    tags: ['按钮', 'Button'],
    version: '1.0.0',
    description: '用于触发操作的按钮组件',
    icon: 'button-icon',
  },
  {
    componentId: 4,
    componentName: 'Image',
    componentType: ComponentTypeEnum.IMAGE,
    category: ComponentCategoryEnum.BASIC,
    tags: ['图片', 'Image'],
    version: '1.0.0',
    description: '用于显示图片的组件',
    icon: 'image-icon',
  },
  {
    componentId: 5,
    componentName: 'Input',
    componentType: ComponentTypeEnum.INPUT,
    category: ComponentCategoryEnum.BASIC,
    tags: ['输入框', 'Input'],
    version: '1.0.0',
    description: '用于用户输入的组件',
    icon: 'input-icon',
  },
  {
    componentId: 6,
    componentName: 'Slider',
    componentType: ComponentTypeEnum.SLIDER,
    category: ComponentCategoryEnum.BASIC,
    tags: ['滑动条', 'Slider'],
    version: '1.0.0',
    description: '用于选择数值范围的组件',
    icon: 'slider-icon',
  },
  {
    componentId: 7,
    componentName: 'Label',
    componentType: ComponentTypeEnum.LABEL,
    category: ComponentCategoryEnum.BASIC,
    tags: ['标签', 'Label'],
    version: '1.0.0',
    description: '用于显示标签文本的组件',
    icon: 'label-icon',
  },
  {
    componentId: 8,
    componentName: 'Textarea',
    componentType: ComponentTypeEnum.TEXTAREA,
    category: ComponentCategoryEnum.BASIC,
    tags: ['文本域', 'Textarea'],
    version: '1.0.0',
    description: '用于多行文本输入的组件',
    icon: 'textarea-icon',
  },
  {
    componentId: 9,
    componentName: 'Switch',
    componentType: ComponentTypeEnum.SWITCH,
    category: ComponentCategoryEnum.BASIC,
    tags: ['开关', 'Switch'],
    version: '1.0.0',
    description: '用于开关状态切换的组件',
    icon: 'switch-icon',
  },
  {
    componentId: 10,
    componentName: 'Form',
    componentType: ComponentTypeEnum.FORM,
    category: ComponentCategoryEnum.LAYOUT,
    tags: ['表单', 'Form'],
    version: '1.0.0',
    description: '用于表单提交的容器组件',
    icon: 'form-icon',
  },
  {
    componentId: 11,
    componentName: 'Card',
    componentType: ComponentTypeEnum.CARD,
    category: ComponentCategoryEnum.LAYOUT,
    tags: ['卡片', 'Card'],
    version: '1.0.0',
    description: '用于显示卡片内容的组件',
    icon: 'card-icon',
  },
  {
    componentId: 12,
    componentName: 'Calendar',
    componentType: ComponentTypeEnum.CALENDAR,
    category: ComponentCategoryEnum.BASIC,
    tags: ['日历', 'Calendar'],
    version: '1.0.0',
    description: '用于显示日历的组件',
    icon: 'calendar-icon',
  },
  {
    componentId: 13,
    componentName: 'Pagination',
    componentType: ComponentTypeEnum.PAGINATION,
    category: ComponentCategoryEnum.BASIC,
    tags: ['分页', 'Pagination'],
    version: '1.0.0',
    description: '用于分页显示的组件',
    icon: 'pagination-icon',
  },
  {
    componentId: 14,
    componentName: 'Table',
    componentType: ComponentTypeEnum.TABLE,
    category: ComponentCategoryEnum.BASIC,
    tags: ['表格', 'Table'],
    version: '1.0.0',
    description: '用于显示表格数据的组件',
    icon: 'table-icon',
  },
  {
    componentId: 15,
    componentName: 'Menu',
    componentType: ComponentTypeEnum.MENU,
    category: ComponentCategoryEnum.BASIC,
    tags: ['菜单', 'Menu'],
    version: '1.0.0',
    description: '用于显示菜单的组件',
    icon: 'menu-icon',
  },

]

export default initComponentList;