import { type ConfigItem, UiTypeEnum, InputTypeEnum } from "@type/ConfigItem";
import { ConfigItemFieldEnum } from "@type/Config";


const initConfigItem: ConfigItem[] = [
  {
    field: ConfigItemFieldEnum.backgroundColor,
    label: '背景颜色',
    uiType: UiTypeEnum.COLOR_PICKER,
    defaultValue: '#ffffff',
    currentValue: '#ffffff',
  },
  {
    field: ConfigItemFieldEnum.flexWrap,
    label: '换行',
    uiType: UiTypeEnum.SELECT,
    defaultValue: 'nowrap',
    currentValue: 'nowrap',
    options: [
      { label: '换行', value: 'wrap' },
      { label: '不换行', value: 'nowrap' },
    ],
  },
  {
    field: ConfigItemFieldEnum.flexDirection,
    label: '主轴方向',
    uiType: UiTypeEnum.SELECT,
    defaultValue: 'row',
    currentValue: 'row',
    options: [
      { label: '水平方向', value: 'row' },
      { label: '垂直方向', value: 'column' },
    ],
  },
  {
    field: ConfigItemFieldEnum.justifyContent,
    label: '主轴对齐',
    uiType: UiTypeEnum.SELECT,
    defaultValue: 'center',
    currentValue: 'center',
    options: [
      { label: '左对齐', value: 'flex-start' },
      { label: '居中', value: 'center' },
      { label: '右对齐', value: 'flex-end' },
      { label: '均匀分布', value: 'space-around' },
      { label: '两侧分布', value: 'space-between' },
    ],
  },
  {
    field: ConfigItemFieldEnum.alignContent,
    label: '侧轴对齐',
    uiType: UiTypeEnum.SELECT,
    defaultValue: 'center',
    currentValue: 'center',
    options: [
      { label: '左对齐', value: 'flex-start' },
      { label: '居中', value: 'center' },
      { label: '右对齐', value: 'flex-end' },
      { label: '均匀分布', value: 'space-around' },
      { label: '两侧分布', value: 'space-between' },
    ],
  },
  {
    field: ConfigItemFieldEnum.MarginPadding,
    label: '边距',
    uiType: UiTypeEnum.MARGIN_PADDING,
    defaultValue: {
      margin: {
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      },
      padding: {
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      },
    },
    currentValue: {
      margin: {
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      },
      padding: {
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      },
    },
    unit: 'px',
  },
  {
    field: ConfigItemFieldEnum.borderColor,
    label: '边框颜色',
    uiType: UiTypeEnum.COLOR_PICKER,
    defaultValue: '#000000',
    currentValue: '#000000',
  },
  {
    field: ConfigItemFieldEnum.borderWidth,
    label: '边框宽度',
    uiType: UiTypeEnum.INPUT_NUMBER,
    defaultValue: 0,
    currentValue: 0,
    min: 0,
    max: 100,
    step: 1,
    unit: 'px',
  },
  {
    field: ConfigItemFieldEnum.borderRadius,
    label: '边框圆角',
    uiType: UiTypeEnum.INPUT_NUMBER,
    defaultValue: 0,
    currentValue: 0,
    min: 0,
    max: 100,
    step: 1,
    unit: 'px',
  },
  {
    field: ConfigItemFieldEnum.borderStyle,
    label: '边框样式',
    uiType: UiTypeEnum.SELECT,
    defaultValue: 'solid',
    currentValue: 'solid',
    options: [
      { label: '实线', value: 'solid' },
      { label: '虚线', value: 'dashed' },
      { label: '点线', value: 'dotted' },
    ],
  },
  {
    field: ConfigItemFieldEnum.width,
    label: '宽度',
    uiType: UiTypeEnum.INPUT_NUMBER,
    defaultValue: 100,
    currentValue: 100,
    step: 1,
    currentUnit: '%',
    units: [
      { label: 'px', value: 'px' },
      { label: '%', value: '%' },
    ],
    mins: [0, 0],
    maxs: [1000, 100],
  },
  {
    field: ConfigItemFieldEnum.height,
    label: '高度',
    uiType: UiTypeEnum.INPUT_NUMBER,
    defaultValue: 60,
    currentValue: 60,
    step: 1,
    currentUnit: 'px',
    units: [
      { label: 'px', value: 'px' },
      { label: '%', value: '%' },
    ],
    mins: [0, 0],
    maxs: [1000, 100],
  },
  {
    field: ConfigItemFieldEnum.text,
    label: '文字',
    uiType: UiTypeEnum.INPUT,
    placeholder: '请输入文字',
    type: InputTypeEnum.TEXT,
    defaultValue: '',
    currentValue: '',
  },
  {
    field: ConfigItemFieldEnum.fontSize,
    label: '字体大小',
    uiType: UiTypeEnum.INPUT_NUMBER,
    defaultValue: 0,
    currentValue: 0,
    min: 0,
    max: 100,
    step: 1,
    unit: 'px',
  },
  {
    field: ConfigItemFieldEnum.fontWeight,
    label: '字体粗细',
    uiType: UiTypeEnum.SELECT,
    defaultValue: 'normal',
    currentValue: 'normal',
    options: [
      { label: '正常', value: 'normal' },
      { label: '加粗', value: 'bold' },
    ],
  },
  {
    field: ConfigItemFieldEnum.lineHeight,
    label: '行高',
    uiType: UiTypeEnum.INPUT_NUMBER,
    defaultValue: 0,
    currentValue: 0,
    min: 0,
    max: 100,
    step: 1,
    unit: 'px',
  },
  {
    field: ConfigItemFieldEnum.color,
    label: '字体颜色',
    uiType: UiTypeEnum.COLOR_PICKER,
    defaultValue: '#000000',
    currentValue: '#000000',
  },
]

export default initConfigItem;